# Generated by Django 4.1.1 on 2023-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Email', models.CharField(default='', max_length=200)),
                ('Telephone', models.CharField(default='', max_length=200)),
                ('ProjectDescription', models.CharField(default='', max_length=200)),
                ('ProductName', models.CharField(default='', max_length=200)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Email', models.CharField(default='', max_length=200)),
                ('Telephone', models.CharField(default='', max_length=200)),
                ('QueryDescription', models.CharField(default='', max_length=200)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
